use_default_settings: true

search:
  default_lang: "en"
  autocomplete: ""
  safe_search: 0
  formats:
    - html
    - json

server:
  secret_key: "bose-search-secret"
  limiter: false
  image_proxy: false

engines:
  - name: github
    weight: 3.0
  - name: stackoverflow
    weight: 3.0
  - name: google
    weight: 1.5
  - name: bing
    weight: 1.0
  - name: duckduckgo
    weight: 1.0
  - name: brave
    weight: 1.0
  - name: youtube
    disabled: true
  - name: dailymotion
    disabled: true
